# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Youngseok Song
email: songy@stat.colostate.edu
description: >- # this means to ignore newlines until "baseurl:"
   Youngseok Song is a PhD Student of Statistics at Colorado State University, Fort Collins, CO.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://enigmasong.github.io/" # the base hostname & protocol for your site
# twitter_username: ander_wilson
github_username:  enigmasong

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

plugins: ['jekyll/scholar']

scholar:
     sort_by: year,month
     order: descending

includes_dir     : ./_includes

header_pages:
  - index.md
  - publications.md
  - teaching.md

# Google services
google_analytics: UA-142123820-1



# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
